print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
num_of_people = int(input("How many people to split the bill? "))
bill_per_person = round((((tip / 100) * bill) + bill) / num_of_people, 2)
print(f"Each person should pay: ${bill_per_person}")